import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ReduxProvider from "./ReduxProvider";
import { Toaster } from "sonner";
import Footer from "@/components/footer/Footer";

// Load Poppins font
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // you can choose weights you need
});

export const metadata: Metadata = {
  title: "Real Estate App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-gray-100/80`}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
          <Toaster position="top-right" richColors />
        </ReduxProvider>
      </body>
    </html>
  );
}
